//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adjustment
    {
        public int AdjustmentId { get; set; }
        public string AdjustmentReason { get; set; }
        public int ProductId { get; set; }
        public int AdjustedQuantity { get; set; }
        public DateTime AdjustedDateTime { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
