//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManufactureProduct
    {
        public int ManufactureProductId { get; set; }
        public int ProductId { get; set; }
        public int ManufactureId { get; set; }
        public string ManufactureCost { get; set; }
        public  DateTime ManufactureDateTime { get; set; }
        public int Quantity { get; set; }
        public virtual Product Product { get; set; }
    }
}
