//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Sale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sale()
        {
            this.ProductSales = new HashSet<ProductSale>();
            this.SaleHolds = new HashSet<SaleHold>();
        }
    
        public int SaleId { get; set; }
        public int ProductId { get; set; }
        public int TransactionId { get; set; }
        [Display(Name = "Invoice Number")]
        public int InvoiceNumber { get; set; }
        public int CustomerId { get; set; }
        [Display(Name = "Sale Date")]
        public DateTime SaleDateTime { get; set; }
        [Display(Name = "Item Total")]
        public decimal ItemTotal { get; set; }
        [Display(Name = "Vat")]
        public decimal Vat { get; set; }
        public decimal Discount { get; set; }
        [Display(Name = "Total Amount")]
        public decimal TotalAmoun { get; set; }

        public virtual Product Product { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSale> ProductSales { get; set; }
        public virtual Transaction Transaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleHold> SaleHolds { get; set; }
    }
}
