//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleHold
    {
        public int SaleHoldId { get; set; }
        public int ProductId { get; set; }
        public String SaleHoldName { get; set; }
        public decimal SaleHoldPrice { get; set; }
        public decimal SaleHoldTotalPrice { get; set; }
        public System.DateTime SaleHoldDateTime { get; set; }
        public int CustomerId { get; set; }
        public int SaleHoldQuantity { get; set; }
        public int SaleId { get; set; }
        public int TransactionId { get; set; }
    
        public virtual Sale Sale { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
