//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionId { get; set; }
        public int SaleId { get; set; }
        public System.DateTime SaleDateTime { get; set; }
        public string TransactionCost { get; set; }
        public string ReceiveAmount { get; set; }
        public string ChangeAmount { get; set; }
    
        public virtual Sale Sale { get; set; }
    }
}
